/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AddRoute } from '../pages/add';
import { Route as _EditRoute } from '../pages/edit';
import { Route as _HistoryRoute } from '../pages/history';
import { Route as _IndexRoute } from '../pages/';
import { Route as _ManageRoute } from '../pages/manage';
import { Route as _PresetRoute } from '../pages/preset';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/add': (typeof _AddRoute)['_inputType'];
    '/edit': (typeof _EditRoute)['_inputType'];
    '/history': (typeof _HistoryRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/manage': (typeof _ManageRoute)['_inputType'];
    '/preset': (typeof _PresetRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/add': (typeof _AddRoute)['_outputType'];
    '/edit': (typeof _EditRoute)['_outputType'];
    '/history': (typeof _HistoryRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/manage': (typeof _ManageRoute)['_outputType'];
    '/preset': (typeof _PresetRoute)['_outputType'];
  }
}
