/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AddRoute } from '../pages/add';
import { Route as _CardRoute } from '../pages/card';
import { Route as _FindRoute } from '../pages/find';
import { Route as _HistoryRoute } from '../pages/history';
import { Route as _IndexRoute } from '../pages/';
import { Route as _ManageRoute } from '../pages/manage';
import { Route as _SetupRoute } from '../pages/setup';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/add': (typeof _AddRoute)['_inputType'];
    '/card': (typeof _CardRoute)['_inputType'];
    '/find': (typeof _FindRoute)['_inputType'];
    '/history': (typeof _HistoryRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/manage': (typeof _ManageRoute)['_inputType'];
    '/setup': (typeof _SetupRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/add': (typeof _AddRoute)['_outputType'];
    '/card': (typeof _CardRoute)['_outputType'];
    '/find': (typeof _FindRoute)['_outputType'];
    '/history': (typeof _HistoryRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/manage': (typeof _ManageRoute)['_outputType'];
    '/setup': (typeof _SetupRoute)['_outputType'];
  }
}
